### ISSUE TITLE
proxy.port is required to be filled in

### ISSUE THREAD

**Issue by sdressler** [MikeSafonov/prometheus-telegram-alert#2]
On commit SHA `89332ed6`, the app refuses to start when `prometheus.telegram.proxy.port` in `application.properties` is not filled in. Setting it to e.g. `-1` works.

> 09:52:33.928 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.boo
t.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'telegramProperties': Could not bind properties to 'TelegramProperties' : prefix=prometheus.telegram, ignoreInvalidFields=false, ignoreUnkno
wnFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'prometheus.telegram.proxy.port' to int

**Comment by MikeSafonov** [comment]
Thanks!
Now fixed at 6f38fd72ec5b3b82ece6ef675669350656f87b33
