### ISSUE TITLE
Build fails with extra .jar

### ISSUE THREAD

**Issue by rewt** [MikeSafonov/prometheus-telegram-alert#20]
https://github.com/MikeSafonov/prometheus-telegram-alert/blob/5b7fbee1837af93f62ddbabfd0de801ea6ba98af/Dockerfile#L12

Remove the extra .jar and build succeeds :)

**Comment by MikeSafonov** [comment]
Thanks!
Fixed in 091d5ca53dd7df342501e94cd076524583301916
